### ISSUE TITLE
Module networks not  found

### ISSUE THREAD

**Issue by Tang-RH** [CaixdLab/CL4CaPro#1]
Dear developers,
Thank you for the detailed documentation on this work, I am very interested in the work presented in this repository and would like to reproduce the results. I have chosen BRCA as a demo to train a Cox model, following the content of TrainCL4CaPro.ipynb. I have completed the preliminary training data preparation and generated the WholeTimeSeq Dataset for Cox:
```
DataSet/
├── CancerRNA_BRCA_WholeTimeSeq_10.txt
├── CancerRNA_BRCA_WholeTimeSeq_12.txt
├── CancerRNA_BRCA_WholeTimeSeq_6.txt
└── CancerRNA_BRCA_WholeTimeSeq_8.txt
```
When I proceed to train the model with the following command:
```
! python Auto_Train_GPU.py --cancer_group {Cancer_Name} --task Cox
```
I encounter errors:
```
 python Auto_Train_GPU.py --cancer_group BRCA --task Cox --num_threads 1
Execute following: python main_CLCP.py --dataset CancerRNA --model_in_dim 20531 --model_n_hidden_1 5196 --model_out_dim 2048 --feat_dim 256 --batch_size 110 --train_test 80 --split_seed 10 --save_freq 5000 --epochs 5000 --learning_rate 2e-05 --round 1 --lr_decay_epochs 0 --l2_rate 0.001 --split_class_num 2 --os W --task WholeTimeSeq --cancer_group BRCA --gpu_device 0
Traceback (most recent call last):
  File "main_CLCP.py", line 620, in <module>
    main()
  File "main_CLCP.py", line 513, in main
    train_loader, val_loader = set_loader(opt)
  File "main_CLCP.py", line 196, in set_loader
    data_get = pd.read_csv(TotalCancerDataPath)
  File "/cluster2/huanglab/rtang/conda/envs/CL4CaPro_L/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 912, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/cluster2/huanglab/rtang/conda/envs/CL4CaPro_L/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 577, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/cluster2/huanglab/rtang/conda/envs/CL4CaPro_L/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1407, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/cluster2/huanglab/rtang/conda/envs/CL4CaPro_L/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1661, in _make_engine
    self.handles = get_handle(
  File "/cluster2/huanglab/rtang/conda/envs/CL4CaPro_L/lib/python3.8/site-packages/pandas/io/common.py", line 859, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: './DataSet/CancerRNA_BRCA_WholeTimeSeq_2.txt'
Execute following: python GenerateFeatures.py --layer_name layer1 --model_in_dim 20531 --dim_1_list 5196 --dim_2_list 2048 --dim_3_list 256 --batch_size 110 --l2_rate 0.001 --seed 10 --round 1 --gpu_device 0 --learning_rate_list 2e-05 --split_class_num 2 --task WholeTimeSeq --cancer_group BRCA
Traceback (most recent call last):
  File "GenerateFeatures.py", line 5, in <module>
    from networks.resnet_big import activation21mlpl2CLCPnet as CLCPnet
ModuleNotFoundError: No module named 'networks'
```
Is networks a custom module, and if so, where can I download it? Also, is it necessary to manually generate the CancerRNA_BRCA_WholeTimeSeq_2.txt file?
Here is my system information:
```
Click to view session information
-----
numpy               1.24.3
openpyxl            3.1.5
pandas              2.0.3
session_info        1.0.0
-----
Click to view modules imported as dependencies
PIL                 9.4.0
asttokens           NA
backcall            0.2.0
bottleneck          1.3.5
cffi                1.15.1
comm                0.2.2
cython_runtime      NA
dateutil            2.8.2
debugpy             1.8.5
decorator           5.1.1
et_xmlfile          2.0.0
executing           2.1.0
google              NA
importlib_metadata  NA
ipykernel           6.29.5
jedi                0.19.1
mkl                 2.4.0
mpl_toolkits        NA
numexpr             2.8.4
packaging           23.0
parso               0.8.4
pexpect             4.9.0
pickleshare         0.7.5
platformdirs        4.3.6
prompt_toolkit      3.0.48
psutil              5.9.0
ptyprocess          0.7.0
pure_eval           0.2.3
pyarrow             11.0.0
pydev_ipython       NA
pydevconsole        NA
pydevd              2.9.5
pydevd_file_utils   NA
pydevd_plugins      NA
pydevd_tracing      NA
pygments            2.18.0
pytz                2022.7
six                 1.16.0
stack_data          0.6.2
tornado             6.4.1
traitlets           5.14.3
typing_extensions   NA
wcwidth             0.2.13
zipp                NA
zmq                 26.1.1
-----
IPython             8.12.2
jupyter_client      8.6.3
jupyter_core        5.7.2
-----
Python 3.8.17 (default, Jul  5 2023, 21:04:15) [GCC 11.2.0]
Linux-4.18.0-372.9.1.el8.x86_64-x86_64-with-glibc2.17
-----
Session information updated at 2024-12-09 08:45
```

I would appreciate any guidance on resolving these issues. Thank you for your time and assistance.

**Comment by Tang-RH** [comment]
The ```activation21mlpl2CLCPnet``` is defined in the CLCPnet.py, convert
```
from networks.resnet_big import activation21mlpl2CLCPnet as CLCPnet
```
to
```
from CLCPnet import activation21mlpl2CLCPnet as CLCPnet
```
will solve the problem.
For CancerRNA_BRCA_WholeTimeSeq_2.txt, change the ```split_class_num``` in Auto_train_GPU.py will solve the problem.
